wandb:
  entity: thatguy11325
  project: pokemon
  group: ~

debug:
  env:
    headless: False
    stream_wrapper: False
    init_state: "Bulbasaur"
    state_dir: pyboy_states
    max_steps: 19000
    log_frequency: 1
    disable_ai_actions: True
    use_global_map: False
    reduce_res: True
    animate_scripts: True
    save_state: False
    save_video: True
    auto_flash: True
    disable_wild_encounters: False
    auto_teach_cut: False
    auto_use_cut: False
    auto_use_strength: False
    auto_use_surf: False
    auto_teach_surf: False
    auto_teach_strength: False
    auto_solve_strength_puzzles: False
    auto_remove_all_nonuseful_items: False
    auto_pokeflute: False
    auto_next_elevator_floor: False
    skip_safari_zone: False
    infinite_safari_steps: False
    insert_saffron_guard_drinks: False
    perfect_ivs: False
  train:
    device: cpu
    compile: False
    compile_mode: default
    num_envs: 1
    envs_per_worker: 1
    num_workers: 1
    env_batch_size: 128
    zero_copy: False
    batch_size: 1024
    minibatch_size: 128
    batch_rows: 4
    bptt_horizon: 2
    total_timesteps: 1_000_000
    save_checkpoint: True
    checkpoint_interval: 4
    save_overlay: True
    overlay_interval: 1
    verbose: True
    env_pool: False
    load_optimizer_state: False
    async_wrapper: False
    sqlite_wrapper: False
    archive_states: False

env:
  headless: True
  save_final_state: True
  print_rewards: True
  video_dir: video
  state_dir: pyboy_states
  init_state: Bulbasaur
  action_freq: 24
  max_steps: 19816
  save_video: False
  fast_video: False
  frame_stacks: 1
  perfect_ivs: False
  reduce_res: True
  two_bit: True
  log_frequency: 2000
  auto_flash: True
  disable_wild_encounters: False
  disable_ai_actions: False
  auto_teach_cut: False
  auto_use_cut: False
  auto_use_strength: True
  auto_use_surf: False
  auto_teach_surf: False
  auto_teach_strength: True
  auto_solve_strength_puzzles: True
  auto_remove_all_nonuseful_items: True
  auto_pokeflute: False
  auto_next_elevator_floor: False
  skip_safari_zone: False
  infinite_safari_steps: False
  insert_saffron_guard_drinks: False
  infinite_money: True
  use_global_map: False
  save_state: True
  animate_scripts: False
  exploration_inc: 1.0
  exploration_max: 1.0
  max_steps_scaling: 0 # 0.2 # every 10 events or items gained, multiply max_steps by 2
  map_id_scalefactor: 9.0 # multiply map ids whose events have not been completed by 10

train:
  seed: 1
  torch_deterministic: True
  device: cuda
  compile: True
  compile_mode: "reduce-overhead"
  float32_matmul_precision: "high"
  total_timesteps: 1_000_000_000 # 100_000_000_000 for full games
  batch_size: 65536
  minibatch_size: 2048
  anneal_lr: False
  num_minibatches: 4
  update_epochs: 3
  norm_adv: True
  ent_coef: 0.010001337
  gae_lambda: 0.9499
  gamma: 0.99799
  clip_coef: 0.1
  clip_vloss: True
  learning_rate: 0.00019999482124740103
  max_grad_norm: 0.5
  target_kl: ~
  vf_clip_coef: 0.1
  vf_coef: 0.5319333384064214
  batch_rows: 128
  bptt_horizon: 16

  num_envs: 288
  num_workers: 24
  env_batch_size: 36
  env_pool: True
  zero_copy: False

  verbose: False
  data_dir: runs
  save_checkpoint: False
  checkpoint_interval: 200
  save_overlay: True
  overlay_interval: 100
  cpu_offload: False
  pool_kernel: [0]
  load_optimizer_state: False
  use_rnn: True
  async_wrapper: False
  sqlite_wrapper: True
  archive_states: True
  swarm: True
  early_stop:
    # event name: minutes. If we dont satisfy each condition
    # we early stop
    # The defaults have a margin of error
    EVENT_BEAT_BROCK: 30
    EVENT_BEAT_MISTY: 300
    EVENT_GOT_HM01: 600
    EVENT_BEAT_ROUTE_9_TRAINER_0: 1200
  one_epoch:
    - "EVENT_BEAT_CHAMPION_RIVAL"
    # - HM_03
    # - HM_04
    # - "EVENT_BEAT_ERIKA"

wrappers:
  empty:
    - episode_stats.EpisodeStatsWrapper: {}

  baseline:
    - stream_wrapper.StreamWrapper:
        user: thatguy
    - exploration.DecayWrapper:
        step_forgetting_factor:
          npc: 0.995
          coords: 0.9995
          map_ids: 0.995
          explore: 0.9995
          start_menu: 0.998
          pokemon_menu: 0.998
          stats_menu: 0.998
          bag_menu: 0.998
          action_bag_menu: 0.998
        forgetting_frequency: 10
    - exploration.OnResetExplorationWrapper:
        full_reset_frequency: 1
        jitter: 0

  finite_coords:
    - stream_wrapper.StreamWrapper:
        user: thatguy
    - exploration.MaxLengthWrapper:
        capacity: 1750
    - exploration.OnResetExplorationWrapper:
        full_reset_frequency: 1
        jitter: 0

  stream_only:
    - stream_wrapper.StreamWrapper:
        user: thatguy
    - exploration.OnResetExplorationWrapper:
        full_reset_frequency: 1
        jitter: 1

  fixed_reset_value:
    - stream_wrapper.StreamWrapper:
        user: thatguy
    - exploration.OnResetLowerToFixedValueWrapper:
        fixed_value:
          coords: 0.33
          map_ids: 0.33
          npc: 0.33
          cut: 0.33
          explore: 0.33
    - exploration.OnResetExplorationWrapper:
        full_reset_frequency: 25
        jitter: 0
    - episode_stats.EpisodeStatsWrapper: {}

rewards:
  baseline.BaselineRewardEnv:
    reward:
  baseline.TeachCutReplicationEnv:
    reward:
      event: 1.0
      bill_saved: 5.0
      seen_pokemon: 4.0
      caught_pokemon: 4.0
      obtained_move_ids: 4.0
      hm_count: 10.0
      level: 1.0
      badges: 10.0
      exploration: 0.02
      cut_coords: 1.0
      cut_tiles: 1.0
      start_menu: 0.01
      pokemon_menu: 0.1
      stats_menu: 0.1
      bag_menu: 0.1

  baseline.TeachCutReplicationEnvFork:
    reward:
      event: 1.0
      bill_saved: 5.0
      obtained_move_ids: 4.0
      hm_count: 10.0
      badges: 10.0
      exploration: 0.02
      cut_coords: 1.0
      cut_tiles: 1.0
      start_menu: 0.01
      pokemon_menu: 0.1
      stats_menu: 0.1
      bag_menu: 0.1
      taught_cut: 10.0
      explore_npcs: 0.02
      explore_hidden_objs: 0.02

  baseline.CutWithObjectRewardsEnv:
    reward:
      event: 1.0
      bill_saved: 5.0
      seen_pokemon: 4.0
      caught_pokemon: 4.0
      obtained_move_ids: 4.0
      hm_count: 10.0
      level: 1.0
      badges: 10.0
      exploration: 0.02
      cut_coords: 0.0
      cut_tiles: 0.0
      start_menu: 0.00
      pokemon_menu: 0.0
      stats_menu: 0.0
      bag_menu: 0.1
      rocket_hideout_found: 5.0
      explore_hidden_objs: 0.02
      seen_action_bag_menu: 0.1

  baseline.CutWithObjectRewardRequiredEventsEnv:
    reward:
      event: 1.0
      seen_pokemon: 4.0
      caught_pokemon: 4.0
      obtained_move_ids: 4.0
      hm_count: 10.0
      level: 1.0
      badges: 5.0
      exploration: 0.02
      cut_coords: 0.0
      cut_tiles: 0.0
      start_menu: 0.0
      pokemon_menu: 0.0
      stats_menu: 0.0
      bag_menu: 0.0
      explore_hidden_objs: 0.02
      seen_action_bag_menu: 0.0
      required_event: 5.0
      required_item: 5.0
      useful_item: 1.0
      pokecenter_heal: 1.0

  baseline.ObjectRewardRequiredEventsEnvTilesetExploration:
    reward:
      event: 1.0
      seen_pokemon: 4.0
      caught_pokemon: 4.0
      obtained_move_ids: 4.0
      hm_count: 10.0
      level: 1.0
      badges: 5.0
      cut_coords: 0.0
      cut_tiles: 0.0
      start_menu: 0.0
      pokemon_menu: 0.0
      stats_menu: 0.0
      bag_menu: 0.0
      explore_hidden_objs: 0.01
      explore_signs: 0.015
      seen_action_bag_menu: 0.0
      required_event: 5.0
      required_item: 5.0
      useful_item: 1.0
      pokecenter_heal: 0.2
      exploration: 0.02
      exploration_gym: 0.025
      exploration_facility: 0.11
      exploration_plateau: 0.025
      exploration_lobby: 0.035 # for game corner
      a_press: 0.0 # 0.00001
      explore_warps: 0.05
      use_surf: 0.05

  baseline.ObjectRewardRequiredEventsMapIds:
    reward:
      a_press: 0.0 # 0.00001
      badges: 3.0
      bag_menu: 0.0
      caught_pokemon: 2.5
      valid_cut_coords: 1.5
      event: .75
      exploration: 0.018999755680454297
      explore_hidden_objs: 0.00009999136567868017
      explore_signs: 0.015025767686371013
      explore_warps: 0.010135211705238394
      hm_count: 7.5
      invalid_cut_coords: 0.0001
      level: 1.05
      obtained_move_ids: 4.0
      pokecenter_heal: 0.47
      pokemon_menu: 0.0
      required_event: 7.0
      required_item: 3.0
      seen_action_bag_menu: 0.0
      seen_pokemon: 2.5
      start_menu: 0.0
      stats_menu: 0.0
      use_surf: 0.4
      useful_item: 0.825
      safari_zone: 3.4493650422686217

  baseline.ObjectRewardRequiredEventsMapIdsFieldMoves:
    reward:
      a_press: 0.0 # 0.00001
      badges: 1.9426719546318056
      bag_menu: 0.0981288719177246
      caught_pokemon: 3.076385498046875
      cut_tiles: 0.9939162135124208
      event: 0.7267916798591614
      exploration: 0.02902716636657715
      explore_hidden_objs: 0.00000101456356048584
      explore_signs: 0.01442893123626709
      explore_warps: 0.01322316527366638
      hm_count: 8.083643913269043
      invalid_cut_coords: 0.0012159876823425292
      invalid_pokeflute_coords: 0.0010716800689697266
      invalid_surf_coords: 0.0010805776119232175
      level: 1.098945999145508
      obtained_move_ids: 4.091134548187256
      pokecenter_heal: 0.5932707786560059
      pokemon_menu: 0.09460494995117188
      pokeflute_tiles: 0.9939162135124208
      required_event: 7.134671688079834
      required_item: 3.3519155979156494
      safari_zone: 10.2822847366333
      seen_action_bag_menu: 0.0
      seen_pokemon: 2.1898984909057617
      start_menu: 0.010755150794982913
      stats_menu: 0.09938607215881348
      surf_tiles: 0.9939162135124208
      use_surf: 0.0
      useful_item: 1.19
      use_ball_count: -10.0
      valid_cut_coords: 4.822387218475342
      valid_pokeflute_coords: 4.840555191040039
      valid_surf_coords: 4.8967742919921875

policies:
  multi_convolutional.MultiConvolutionalPolicy:
    policy:
      hidden_size: 512

    rnn:
      # Assumed to be in the same module as the policy
      name: MultiConvolutionalRNN
      args:
        input_size: 512
        hidden_size: 512
        num_layers: 1
