env:
  max_steps:
    carbs.utils.LinearSpace:
      min: 10240
      max: 81920
      is_integer: True
      scale: 2500
  map_id_scalefactor:
    carbs.utils.LinearSpace:
      min: 5.0
      max: 20.0
      scale: 1.0

train:
  total_timesteps:
    carbs.utils.LinearSpace:
      min: 500_000_000
      max: 10_000_000_000
      is_integer: True
      scale: 100_000_000
  learning_rate:
    carbs.utils.LogSpace:
      min: 1.0e-5
      max: 1.0e-3
      scale: 1.0e-4
  gamma:
    carbs.utils.LogitSpace:
      min: .75
      max: 1.0
      scale: .0005
  gae_lambda:
    carbs.utils.LogitSpace:
      min: .75
      max: 1.0
      scale: .01
  ent_coef:
    carbs.utils.LogSpace:
      min: 1.0e-5
      max: 1.0e-1
      scale: .005
  vf_coef:
    carbs.utils.LogSpace:
      min: 1e-1
      max: 1.0
      scale: .05

rewards:
  baseline.ObjectRewardRequiredEventsMapIdsFieldMoves:
    reward:
      caught_pokemon:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      badges:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 10.0
          scale: 1.5
      bag_menu:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 0.5
          scale: 1e-2
      cut_tiles:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 5
          scale: .25
      event:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 0.5
      exploration:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 1.0
          scale: 0.01
      explore_hidden_objs:
        carbs.utils.LinearSpace:
          min: 1.0e-7
          max: 1.0
          scale: 5e-5
      explore_signs:
        carbs.utils.LinearSpace:
          min: 1.0e-4
          max: 1.0
          scale: 1e-3
      explore_warps:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 0.005
      hm_count:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 15.0
          scale: 1.0
      invalid_cut_coords:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 1.0e-1
          scale: 5e-4
      invalid_pokeflute_coords:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 1.0e-1
          scale: 5e-4
      invalid_surf_coords:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 1.0e-1
          scale: 5e-4
      level:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 10.0
          scale: 0.1
      moves_obtained:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      pokecenter_heal:
        carbs.utils.LinearSpace:
          min: 1.0e-4
          max: 10.0
          scale: 0.1
      pokemon_menu:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 0.5
          scale: 1e-2
      required_event:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      required_item:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      safari_zone:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 15.0
          scale: 0.5
      seen_pokemon:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      start_menu:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 0.1
          scale: 1e-3
      stats_menu:
        carbs.utils.LinearSpace:
          min: 1.0e-5
          max: 0.5
          scale: 1e-2
      valid_cut_coords:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1
      valid_pokeflute_coords:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1
      valid_surf_coords:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1
      useful_item:
        carbs.utils.LinearSpace:
          min: 1.0e-3
          max: 10.0
          scale: 0.5
# policies:
#   multi_convolutional.MultiConvolutionalPolicy:
#     policy:
#       hidden_size:
#         carbs.utils.LinearSpace:
#           min: 512
#           max: 1024
#           is_integer: True

#     rnn:
#       # Assumed to be in the same module as the policy
#       name: MultiConvolutionalRNN
#       args:
#         input_size:
#           carbs.utils.LinearSpace:
#             min: 512
#             max: 2048
#             is_integer: True
#         hidden_size:
#           carbs.utils.LinearSpace:
#             min: 512
#             max: 2048
#             is_integer: True

