rewards:
  baseline.ObjectRewardRequiredEventsMapIds:
    reward:
      event: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 0.5
      seen_pokemon: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      caught_pokemon: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      obtained_move_ids: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      hm_count: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 15.0
          scale: 1.0
      level: 
        carbs.utils.LogSpace:
          min: 1.0e-5
          max: 10.0
          scale: 0.1
      badges: 
        carbs.utils.LogSpace:
          min: 1.0e-5
          max: 10.0
          scale: 2.0
      explore_hidden_objs: 
        carbs.utils.LogSpace:
          min: 1.0e-7
          max: 1.0
          scale: 5e-5
      explore_signs: 
        carbs.utils.LogSpace:
          min: 1.0e-4
          max: 1.0
          scale: 1e-3
      required_event: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      required_item: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 1.0
      useful_item: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 0.5
      pokecenter_heal: 
        carbs.utils.LogSpace:
          min: 1.0e-4
          max: 10.0
          scale: 0.1
      exploration: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 1.0
          scale: 0.01
      explore_warps: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 10.0
          scale: 0.005
      use_surf: 
        carbs.utils.LogSpace:
          min: 1.0e-3
          max: 2.0
          scale: 0.25
# policies:
#   multi_convolutional.MultiConvolutionalPolicy:
#     policy:
#       hidden_size:
#         carbs.utils.LinearSpace:
#           min: 512
#           max: 1024
#           is_integer: True

#     rnn:
#       # Assumed to be in the same module as the policy
#       name: MultiConvolutionalRNN
#       args:
#         input_size:
#           carbs.utils.LinearSpace:
#             min: 512
#             max: 2048
#             is_integer: True
#         hidden_size:
#           carbs.utils.LinearSpace:
#             min: 512
#             max: 2048
#             is_integer: True

